spring.datasource.url=jdbc:postgresql://localhost:5432/is
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.show_sql=true
spring.jpa.open-in-view=false
minio.endpoint=http://localhost:9000
minio.accessKey=GjN8mHq0o2x7SyEe17v8
minio.secret-key=P5iDdHzCy0Sapgqm9EhctzKUMka3TDVB9o9yAcwr
minio.bucket=test